### ISSUE TITLE
大佬您好，你知道unlocker解锁角色文件的原理吗，我也做过关于本地服b30生成的内容属于是同道中人了ww(，目前想开发一个带gui界面的unlocker总是查找到角色id再手动去拿unlocker解锁很麻烦，谢谢！

### ISSUE THREAD

**Issue by mizuhara27** [MonianHello/ottoNET#1]

**Comment by MonianHello** [comment]
- 对于乐曲:
将xml文件中的`<firstLock>true</firstLock>`替换为`<firstLock>false</firstLock>`

- 对于活动:
将xml文件中的`<alwaysOpen>false</alwaysOpen>`替换为`<alwaysOpen>true</alwaysOpen>`

- 对于收藏品(语音、姓名框、角色、跑图小人、称号等):
将xml文件中的`<defaultHave>false</defaultHave>`替换为`<defaultHave>true</defaultHave>`

希望能帮到你

**Comment by mizuhara27** [comment]
非常感谢！
